import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { cookies } from "next/headers";
import "./globals.css";
import { getImageMarket, getMyMarket, getProfile } from "@/untils/SessionProviders";
import { AuthProvider } from "@/untils/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const getcookie = cookieStore.get('Authentication')
  const getDataProfile = await getProfile()
  const getDataMyMarket = await getMyMarket()
  const getMarketsImage = await getImageMarket()
  return (
    <AuthProvider value={{
        getcookie:getcookie?.value,
        getprofile:getDataProfile?.data,
        getmymarket:getDataMyMarket,
        getMarketsImage:getMarketsImage
      }
    }>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className='bg-gray-100'>
            <nav className="bg-white border-gray-200 dark:bg-gray-900 mb-3">
              <Navbar getcookie={getcookie}/>
            </nav>
            <main className="mx-3 flex flex-col gap-8 row-start-2 items-center sm:items-start">
              {children}
            </main>
            <footer className="mt-4">
              <Footer />
            </footer>
          </div> 
        </body>
      </html>
    </AuthProvider>
  );
}
